<?php

namespace OrderBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TestentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestentityRepository extends EntityRepository
{
}
