OrderBundle\Entity\Testentity:
    type: entity
    table: null
    repositoryClass: OrderBundle\Repository\TestentityRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        test:
            type: string
            length: 255
    lifecycleCallbacks: {  }
